news:
    path: /
    controller: App\Controller\ArticleAdminController::list

article_toggle_heart:
    path: /news/{slug}/heart
    controller: App\Controller\DefaultController::toggleArticleHeart
    methods:  [POST]

add_article:
    path: /admin/article/new
    controller: App\Controller\ArticleAdminController::new

list_article:
    path: /admin/article/list
    controller: App\Controller\ArticleAdminController::list