index:
    path: /
    controller: App\Controller\DefaultController::index

news:
    path: /news/{slug}
    controller: App\Controller\DefaultController::show

article_toggle_heart:
    path: /news/{slug}/heart
    controller: App\Controller\DefaultController::toggleArticleHeart
    methods:  [POST]